### ISSUE TITLE
Problems with transparency on custom background color

### ISSUE THREAD

**Issue by Incubbus** [apache/cordova-plugin-statusbar#149]
# Bug Report

## Problem

No transparency when using `backgroundColorByHexString("#BB000000")` and `this.statusBar.overlaysWebView(true);`.

### What is expected to happen?

The status bar should be an overlay on the web view and shoul be kinda transparent.

### What does actually happen?

The status bar is behaving as if `this.statusBar.overlaysWebView(false);` was called and the color is dark gray-ish..

### Command or Code

``
this.statusBar.backgroundColorByHexString("#BB000000");
this.statusBar.overlaysWebView(true);
``

and 

``
this.statusBar.overlaysWebView(true);
this.statusBar.backgroundColorByHexString("#BB000000");
``

have been tested

### Environment, Platform, Device

Ionic, Cordova, on Android 6.0.1 and Android 9.

### Version information

```
Ionic:

   Ionic CLI          : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-webview 1.2.1, (and 19 other plugins)
```

## Checklist

- [x] I searched for existing GitHub issues (according to suggested issues)
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
What you are trying to do is a conflict. Overlay statusbars must be transparent. They are not solid and cannot have a color applied to them. Therefore by calling `backgroundColorByHexString` afterwards, the native code must remove the translucent flags required to make it an overlay, so the statusbar becomes a solid again so that a color can be applied.

If you want an overlayed statusbar but still want to apply a background color to it, I'd suggest creating and positioning an HTML div with the desired color. I'll provide a sample css.

```css
.myStatusBarDiv {
    position: fixed;
    top: 0px;
    left: 0px;
    right: 0px;
 /* In my experience, 20px covers all modern phones, but not 100% if this is a safe assumption */
    height: 20px;
    background-color: rgba(0,0,0.73); /* #BB000000, 0xBB = 187 / 255 = 0.73333 */
}
```

Of course, you'd also want to make sure you pad/margin your content by the same height.
